---
title: "Biostatistical Literacy: Project Page"
output: rmdformats::readthedown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rmdformats)
```

# Project Contributors

In alphabetical order: 

- [Laura Le](https://directory.sph.umn.edu/bio/sph-a-z/laura-le)
- [Michael R. Jiroutek](https://directory.campbell.edu/people/michael-jiroutek/)
- [Steven J. Foti](https://biostat.ufl.edu/profile/foti-steven/)
- [V.N. Vimal Rao](https://raovnv.github.io/research.html)

# Introduction to the Project

Being able to critically evaluate quantitative methods used by studies in the medical sciences is an important skill for students in the public health field. These skills are distinct from some of the content traditionally emphasized in introductory statistics and biostatistics classes, such as learning how to run statistical analysis in R or SAS. 

Instead, we teach a course specifically focused on developing students' biostatistical literacy, with a focus on reading methods and results sections and critically evaluating them. The course was originally developed at the University of Minnesota, by Dr. Ann Brearly, but we have each adapted it at our own universities, and adapted it for different course formats and instructional levels. 

The goal of this project is to share our resources with other statistics and biostatistics instructors, describe why and how we implemented these courses and evaluate their efficacy in achieving program-level student learning objectives, and provide a roadmap for other instructors interested in implementing a similar course at their institution. 

# RSS TSS 2024

With the Royal Statistical Society's Teaching Statistics section, we are presenting an online seminar, [Biostatistical Literacy: What is it, and how can we teach it?](https://rss.org.uk/training-events/events/events-2024/sections/biostatistical-literacy-what-is-it,-and-how-can-we/).

Materials: 

- [Slides]()

# USCOTS 2023

At the 2023 US Conference on Teaching Statistics, we are presenting two sessions:

- A breakout session, [Biostatistical Literacy: What it is, and how can we teach it?](https://causeweb.org/cause/uscots/uscots23/3a-biostatistical-literacy-what-it-and-how-can-we-teach-it-room-107)
- A beyond posters session, [Using collaborative keys to promote active learning and student engagement for in-person or online courses](https://causeweb.org/cause/uscots/uscots23/f26-using-collaborative-keys-promote-active-learning-and-student-engagement-person)

Materials: 

- [Slides](https://docs.google.com/presentation/d/1AWS2oLxYb4O2k0JcjnIIibtI-qUJnR7x/edit?usp=sharing&ouid=103368445301151303004&rtpof=true&sd=true) from the breakout session
- [Concept Activity](https://docs.google.com/document/d/1drzU4AJxun_VBEURbbVy1-XrAME9vtHd/edit?usp=sharing&ouid=103368445301151303004&rtpof=true&sd=true) from the breakout session
- [Literature Review Activity](https://docs.google.com/document/d/14Ym6BTXIbREiWPW4zEdDgKuipFzG4Aca/edit?usp=sharing&ouid=103368445301151303004&rtpof=true&sd=true) from the breakout session
- [Poster](https://docs.google.com/presentation/d/1zKy67WV0Z8QzIpf0ZdTUDxIp-NZaYGzA/edit?usp=sharing&ouid=103368445301151303004&rtpof=true&sd=true) from the beyond posters session
- [Collaborative Key Timelapse](https://drive.google.com/file/d/1ftcSxqMgCcSbdljdjWSTfR-u2qaIIRUP/view?usp=sharing) from the beyond posters session

# Our syllabi

Use [this link](https://drive.google.com/drive/folders/1AbqGdDb9WDGaI2jf0LxAKgRd8u05JF95?usp=sharing) to access our curricular materials. 

To see the variety of ways we have implemented this curriculum, use [this link](https://drive.google.com/drive/folders/1rmJWv2Fbnw5Hvogvg1DLLNN0QUNpToaj?usp=sharing) to access our syllabi. 

We encourage you to consider using some in your own course! For questions, please do not hesitate to contact us. 

# Citations

Le, L., Jiroutek, M.R., & Rao, V.N.V. (2024, January). *Biostatistical Literacy: What is it, and how can we teach it?* [Invited Talk]. 
Royal Statistical Society (RSS) Teaching Statistics Section, online. Sponsored by Dr. Elinor Jones and Dr. Jamie Sergeant.  

Foti, S.J., Jiroutek, M.R., Le, L., & Rao, V.N.V. (2023, June). *Biostatistical Literacy: What is it, and how can we teach it?* [Breakout Session]. United States Conference on Teaching Statistics (USCOTS), State College, Pennsylvania. 

Jiroutek, M.R., Le, L., Foti, S.J., & Rao, V.N.V. (2023, June). *Using Collaborative Keys to promote active learning and student engagement for in-person or online courses* [Posters and Beyond Presentation]. United States Conference on Teaching Statistics (USCOTS), State College, Pennsylvania.